name: zcs_printing
description: A Flutter plugin for ZCS/SmartPos printer integration with PDF printing and system print support.
version: 1.0.2+3
homepage: https://github.com/MoltaqaFlutter/zcs_printing_plugin

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  typed_data: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.zcs_printing
        pluginClass: ZcsPrintingPlugin
      ios:
        pluginClass: ZcsPrintingPlugin
